### PR TITLE
fix nethermind chainspec

### PR DESCRIPTION
**Pull request by barnabasbusa**

### CODE REVIEW

**Comment by parithosh** [comment]
Is this a required field in the Nethermind chainspec?

**Comment by barnabasbusa** [comment]
It is required. https://discord.com/channels/595666850260713488/892088344438255616/1055533562453049395

**Review by parithosh — APPROVED** [review]

**Comment by parithosh** [comment]
Please make a new release once you've merged it

**Comment by barnabasbusa** [comment]
Looks like the docker build has failed. 
```sh
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c git clone https://github.com/protolambda/eth2-testnet-genesis.git     && cd eth2-testnet-genesis     && go install .     && go install github.com/protolambda/eth2-val-tools@latest     && go install github.com/protolambda/zcli@latest" did not complete successfully: exit code: 2
```

**Comment by parithosh** [comment]
hmm, let me try it as well. There were some changes recently to eth2-testnet-genesis and it worked locally atleast. But we might need to update go version or something.

**Pull request merged**
