### PR TITLE
Customisable slots per epoch

### PR DESCRIPTION
**Pull request by Tofel**
I found manipulating that variable pretty useful for private testnets, where finalisation speed is more important than network security. Is there a reason why you did not make it configurable from the get go?

### CODE REVIEW

**Comment by parithosh** [comment]
Which clients have you tested this with? AFAIK not all clients support modifying the preset value of slots per epoch. Our approach for faster testing is to reduce the seconds per slot, achieves the same thing and is supported by atleast 4/5 CLs in our experience.

**Comment by parithosh** [comment]
Yeah our go to is usually testing with `3s` slots :) But ofc it could always be faster

There's a concept of a `minimal` config that is supported by all clients. Perhaps that's a better approach to go down, afaik the `minimal` config already supports faster forks and is useful for limited testing scenarios.

**Comment by barnabasbusa** [comment]
I'd personally be against including a variable in the config that is not in the spec:

https://github.com/ethereum/consensus-specs/blob/dev/configs/mainnet.yaml

**Comment by barnabasbusa** [comment]
#104 should fix your issue

**Pull request closed without merging**
